# Generated by Django 4.0.5 on 2022-06-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('discription', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('UI', 'URGENT / IMPORTANT'), ('UN', 'URGENT / NOT-IMPORTANT'), ('NI', 'NOT-URGENT / IMPORTANT'), ('NN', 'NOT-URGENT / NOT-IMPORTANT')], default='UI', max_length=3)),
                ('isCompleted', models.BooleanField()),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'TODOS',
            },
        ),
    ]
