# Generated by Django 4.0.5 on 2022-06-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_todo_create_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={},
        ),
    ]
