# Generated by Django 4.0.5 on 2022-06-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('discription', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('UI', 'URGENT / IMPORTANT'), ('UN', 'URGENT / NOT-IMPORTANT'), ('NI', 'NOT-URGENT / IMPORTANT'), ('NN', 'NOT-URGENT / NOT-IMPORTANT')], default='UI', max_length=3)),
                ('isCompleted', models.BooleanField(default='false')),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'TODOS',
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
