# Generated by Django 4.0.5 on 2022-06-11 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_todo_delete_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TODO',
        ),
    ]
